name: Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker-publish:
    name: 'Build and publish Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set version
        run: |
          (git describe --tags --exact-match \
            || git symbolic-ref -q --short HEAD \
            || git rev-parse --short HEAD) > version.txt 2> /dev/null

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ouuan/wakapi:latest
          platforms: linux/amd64
